function InitCustomUI()
    HideDefaultUI()
    BlzFrameSetVisible(BlzGetFrameByName("UpperButtonBarFrame",0), true)
    BlzFrameSetVisible(BlzGetFrameByName("UpperButtonBarAlliesButton",0), false)
    BlzFrameSetVisible(BlzGetFrameByName("UpperButtonBarChatButton",0), false)
    BlzFrameSetVisible(BlzGetFrameByName("UpperButtonBarQuestsButton",0), false)

    BlzFrameClearAllPoints(BlzGetFrameByName("UpperButtonBarFrame",0))
    BlzFrameSetScale(BlzGetFrameByName("UpperButtonBarFrame",0), 1.5)
    BlzFrameSetAbsPoint(BlzGetFrameByName("UpperButtonBarFrame",0), FRAMEPOINT_TOPLEFT, -0.26065, 0.6)
    BlzFrameSetAbsPoint(BlzGetFrameByName("UpperButtonBarFrame",0), FRAMEPOINT_BOTTOMRIGHT, -0.16065, 0.56)
    ClickBlocker = BlzCreateFrameByType("TEXT", "name", BlzGetFrameByName("ConsoleUIBackdrop", 0), "", 0)
        CreateTextFrame(ClickBlocker, -0.1338, 0.6, 0.936020, 0, 0, "", 1)
            BlzFrameSetEnable(ClickBlocker, true)
    HPBar()
    Icons()
    CreateWarnings()
end